name: Icon list

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: increment-version
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: list directory
        id: list
        run: |
          find icons/ -maxdepth 1 -printf "%f\n" > iconlist.txt

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "update horse list"
          git push
